from typing import Literal

from scapy.all import sniff
from scapy.packet import Packet
from scapy.plist import PacketList
from scapy.layers.l2 import ARP
from scapy.layers.inet import IP, TCP


from src.tp1.utils.args import Args
from src.tp1.utils.config import logger
from src.tp1.utils.lib import choose_interface, contains_sql_injection, find_flags

import inspect


class Attack:
    def __init__(self, type: Literal["arp_spoofing", "port_scan", "sql_injection"], attacker: str):
        """_summary_

        Args:
            type (Literal[&quot;arp_spoofing&quot;, &quot;port_scan&quot;, &quot;sql_injection&quot;]): Attack type
            attacker (str): Attacker MAC or IP
        """
        self.type = type
        self.attacker = attacker

    def to_dict(self) -> dict[str, str]:
        return {"type": self.type, "attacker": self.attacker}

    def __str__(self) -> str:
        return f"({self.type}, {self.attacker})"

    __repr__ = __str__


Protocols = dict[str, int]


class Summary:
    def __init__(
        self, protocols: Protocols | None = None, attacks: list[Attack] | None = None, flag: str = ""
    ) -> None:
        self.protocols = protocols or {}
        self.attacks = attacks or []
        self.flag = flag

    def to_dict(self) -> dict[str, Protocols | str | list[dict[str, str]]]:
        return {
            "protocols": self.protocols,
            "attacks": [a.to_dict() for a in self.attacks],
            "flag": self.flag,
        }

    def __str__(self) -> str:
        return f"Protocols : {self.protocols}\nattacks : {self.attacks}\nFlag : {self.flag}"


class Capture:
    _LAYER_ALIASES = {"Ether": "ETHERNET"}

    def __init__(self, timeout: int = 5, pcap_file: str | None = None, interface: str | None = None) -> None:
        self.interface: str = interface or choose_interface()
        """Interface to sniff if no pcap
        """

        self.pcap_file: str | None = pcap_file or Args.pcap_file or None
        """PCAP file to analyse offline
        """
        self.is_offline: bool = self.pcap_file is not None
        """Is offline is true if pcap_file set
        """

        self.summary: Summary | None = None
        """Summary generated by _gen_summary
        """
        self.attacks: list[Attack] = []
        """Detected attacks
        """
        self.flag: str | None = None
        """Guest flag
        """

        self.captured_packets: PacketList | None = None
        """List of all captured packets
        """

        self._protocols: Protocols = {}
        self._timeout: int = timeout

        self._is_capture_done: bool = False
        self._is_analyse_done: bool = False

    def _handle_packet(self, pkt: Packet) -> None:
        # logger.debug(f"{pkt.summary()}")
        names = {Capture._LAYER_ALIASES.get(p.__name__, p.__name__) for p in pkt.layers()}

        for name in names:
            self._protocols[name] = self._protocols.get(name, 0) + 1

            # TODO Capture HTTP and ETHERNET

    def capture_traffic(self) -> None:
        """
        Capture network traffic from an interface
        """
        if self._is_capture_done:
            logger.warn("Capture launched a second time")

        self._is_analyse_done = False
        self._is_capture_done = False

        packets: PacketList | None = None

        if self.is_offline:
            logger.info(f"Capture offline of {Args.pcap_file}")
            packets = sniff(prn=self._handle_packet, offline=self.pcap_file, timeout=self._timeout)
        else:
            interface = self.interface
            logger.info(
                f"Capture traffic from interface {interface} for {self._timeout} seconds (Press Ctrl + C to interrupt)"
            )

            packets = sniff(prn=self._handle_packet, iface=self.interface, timeout=self._timeout)

        self.captured_packets = packets

        self._is_capture_done = True

        le = len(self.captured_packets or [])

        logger.info(f"{le if le > 0 else 'no'} packet{'s' if le > 1 else ''} captured")

    def sort_network_protocols(self) -> list[str]:
        """
        Sort and return all captured network protocols
        """
        return [k for k, _ in sorted(self._protocols.items(), key=lambda i: i[1], reverse=True)]

    def get_all_protocols(self) -> Protocols:
        """
        Return all protocols captured with total packets number
        """
        return self._protocols.copy()

    def _find_arp_spoofing(self) -> list[Attack]:
        """Search for ARP spoofing by building an arp table

        Returns:
            list[Attack]: List of all attacks if found
        """
        attacks: list[Attack] = []

        if self.captured_packets is None:
            return attacks

        _detected = 0
        _arp_count = 0

        arp_table: dict[str, str] = {}

        for pck in self.captured_packets:  # TODO Correct function to give best result
            if pck.haslayer(ARP):
                _arp_count += 1
                _arp_l = pck.getlayer(ARP)
                if isinstance(_arp_l, ARP):
                    arp_l: ARP = _arp_l
                    mac, src = arp_l.hwsrc, arp_l.psrc

                    if arp_table.get(src, mac) == mac:
                        arp_table[src] = mac

                    else:
                        _detected += 1

                        logger.debug(f"ARP Spoofing detected from {mac}")

                        attacks.append(Attack("arp_spoofing", mac))

        logger.debug(f"{_detected} out of {_arp_count} ARP Spoofing detected !")

        return attacks

    def _find_port_scan(self, threshold: int = 20) -> list[Attack]:
        """Search for port scan by counting TCP SYN packet from same src and dst

        Args:
            threshold (int, optional): Number of different ports to validate port scan. Defaults to 20.

        Returns:
            list[Attack]: List of port scans detected, return empty list if none found
        """
        attacks: list[Attack] = []

        if self.captured_packets is None:
            return attacks

        # (ip src, ip dst) -> ports
        scanned_ports: dict[tuple[str, str], set[int]] = {}

        for pck in self.captured_packets:
            if pck.haslayer(IP) and pck.haslayer(TCP):
                ip_l, tcp_l = pck[IP], pck[TCP]

                if tcp_l.flags == "S":
                    key = (ip_l.src, ip_l.dst)
                    scanned_ports.setdefault(key, set()).add(tcp_l.dport)

        for (src, dst), ports in scanned_ports.items():
            if len(ports) >= threshold:
                logger.debug(f"Port scan detected from {src} on {dst} ({len(ports)} ports)")
                attacks.append(Attack("port_scan", src))

        logger.debug(f"{len(attacks)} port scan detected !")

        return attacks

    def _find_sql_injection(self) -> list[Attack]:
        """Search for SQL injection in the captured packets

        Returns:
            list[Attack]: List of attacks detected, return empty list not found
        """
        attacks: list[Attack] = []

        if self.captured_packets is None:
            return attacks

        _detected = 0

        for pck in self.captured_packets:
            if not (pck.haslayer(IP) and pck.haslayer(TCP)):
                continue

            payload = pck[TCP].payload.load if pck[TCP].payload else ""

            if len(payload) == 0:
                continue

            if contains_sql_injection(payload):
                flags = find_flags(payload)
                if len(flags) == 1:
                    self.flag = flags[0]
                elif len(flags) > 1:
                    logger.warn(f'More than one flag has been found in payload "{payload}"')

                _detected += 1
                src = pck[IP].src

                logger.debug(f"SQL injection ({src}:{pck[TCP].sport} -> {pck[IP].dst}:{pck[TCP].dport})")

                attacks.append(Attack("sql_injection", src))

        logger.debug(f"{_detected} SQL injection detected !")

        return attacks

    def _find_flag(self) -> str | None:
        raise NotImplementedError()

        # logger.debug("Starting search of SQL injection")

        # if self.captured_packets is None: return

        # flags: list[str] = []

        # for pck in self.captured_packets:
        #     if not (pck.haslayer(IP) and pck.haslayer(TCP)):
        #         continue

        #     payload = pck[TCP].payload.load if pck[TCP].payload else ""

        #     if len(payload) == 0:
        #         continue

        #     flags += find_flags(payload)

        # if len(flags) != 1: return

        # return flags[0]

    def analyse(self, protocols: list[str] | str) -> None:
        """
        Analyse all captured data and return statement
        Si un trafic est illégitime (exemple : Injection SQL, ARP
        Spoofing, etc)
        a Noter la tentative d'attaque.
        b Relever le protocole ainsi que l'adresse réseau/physique
        de l'attaquant.
        c (FACULTATIF) Opérer le blocage de la machine
        attaquante.
        Sinon a cher que tout va bien
        """

        if not self._is_capture_done:
            logger.warn("Analyse started without the capture done")

        all_protocols = self.get_all_protocols()
        sort = self.sort_network_protocols()
        logger.debug(f"All protocols: {all_protocols}")
        logger.debug(f"Sorted protocols: {sort}")

        self.attacks += self._find_arp_spoofing()

        self.attacks += self._find_port_scan()

        self.attacks += self._find_sql_injection()

        if len(self.attacks) > 0:
            logger.info(f"{len(self.attacks)} attacks detected out of {len(self.captured_packets or [])}")

        self._is_analyse_done = True

        self.summary = self._gen_summary()

    def get_summary(self) -> Summary | None:
        """
        Return summary
        :return:
        """
        return self.summary

    def _gen_summary(self) -> Summary:
        """
        Generate summary
        """

        if not self._is_analyse_done:
            logger.warn("Summary generation started without the analyse done")

        summary = Summary(self._protocols, self.attacks, self.flag or "")

        _caller = inspect.stack()[1].function

        logger.debug(f"summary generated : \n==== Summary ====\n{summary}\n====\n (from func {_caller})")

        return summary
